restructure to use 1 container folder

diff --git a/containers/.devcontainer/containers/Nop.Web/Dockerfile b/containers/.devcontainer/containers/Nop.Web/Dockerfile
--- a/containers/.devcontainer/containers/Nop.Web/Dockerfile
+++ b/containers/.devcontainer/containers/Nop.Web/Dockerfile
@@ -2,7 +2,7 @@
 # /projects/nopCommerce
 # this devcontainer dockerfile in the ./.devcontainer folder
 
-# create the build instance 
+# create the build instance
 FROM mcr.microsoft.com/dotnet/sdk:9.0-noble AS build
 USER root
 RUN dotnet workload update && \
@@ -36,7 +36,7 @@ RUN if [ "$DEBUG" = "true" ]; then \
     fi
 
 
-    
+
 # Remove container image user and group if they conflict with the remoteUser from docker-compose/devcontainer.json
 # This is important to avoid conflicts with the user and group IDs
 # Step 2: Delete user (if exists)
@@ -91,15 +91,7 @@ RUN set -eux && \
         echo "Verifying user creation..."; \
     fi && \
     getent passwd "${IDE_USER}" || (echo "Error: User ${IDE_USER} was not created!" && exit 1)
-   
-WORKDIR /src
-COPY ["./src/Directory.Build.props", "."]
-COPY ["./src/NopCommerce.sln", "."]
-COPY ["./src/Presentation/Nop.Web/Nop.Web.csproj", "Presentation/Nop.Web/"]
-COPY ["./src/Presentation/Nop.Web.Framework/Nop.Web.Framework.csproj", "Presentation/Nop.Web.Framework/"]
-COPY ["./src/Libraries/Nop.Core/Nop.Core.csproj", "Libraries/Nop.Core/"]
-COPY ["./src/Libraries/Nop.Data/Nop.Data.csproj", "Libraries/Nop.Data/"]
-COPY ["./src/Libraries/Nop.Services/Nop.Services.csproj", "Libraries/Nop.Services/"]
+
 
 # in debug mode, show the current working directory and its contents
 RUN if [ "$DEBUG" = "true" ]; then \
@@ -109,69 +101,61 @@ RUN if [ "$DEBUG" = "true" ]; then \
         ls -l; \
     fi
 
-# we do this twice!!!! this is important to make subsequent re-builds faster
-# The source of the core Nop project does not often change. So this layer will be cached and reused.
-# It prepares the project for building
-# The --disable-parallel option is used to avoid issues with parallel restores
-RUN dotnet restore Presentation/Nop.Web/Nop.Web.csproj --disable-parallel && \
-    dotnet clean Presentation/Nop.Web/Nop.Web.csproj
+###############################################################################
+#                                                                             #
+#      If you want docker to build NopCommerce, uncomment the lines below     #
+#                                                                             #
+###############################################################################
 
-# Copy the solution and project files as root
-WORKDIR /workspace
-COPY . .
-# Ensure ./bin does not exist, because we will create it as $IDE_USER and copy the contents of ./src to ./bin as $IDE_USER
-USER root
-RUN rm -rf ./bin 
+# Copy the source code and build the application
+# # Copy the solution and project files as root
+# COPY ./src ./src
+# # Ensure ./bin does not exist, because we will create it as $IDE_USER and copy the contents of ./src to ./bin as $IDE_USER
+# RUN rm -rf ./bin
 
-# in debug mode, show the current working directory and its contents
-RUN if [ "$DEBUG" = "true" ]; then \
-        echo "Current WORKDIR is:"; \
-        pwd; \
-        echo "Subdirectories under WORKDIR:"; \
-        ls -l; \
-    fi
+# # in debug mode, show the current working directory and its contents
+# RUN if [ "$DEBUG" = "true" ]; then \
+#         echo "Current WORKDIR is:"; \
+#         pwd; \
+#         echo "Subdirectories under WORKDIR:"; \
+#         ls -l; \
+#     fi
 
-RUN dotnet restore src/NopCommerce.sln --disable-parallel && \
-dotnet clean src/NopCommerce.sln
+# RUN dotnet restore src/NopCommerce.sln --disable-parallel && \
+# dotnet clean src/NopCommerce.sln
 
-# Ensure the IDE_USER has ownership of the workspace directory - dont know if this works. copilot says it cannot be done
-# only echo out the status if in debug mode
-RUN set -eux && \
-    echo "Fixing ownership and permissions for /workspace..." && \
-    chown -R ${IDE_USER}:${IDE_USER} /workspace && \
-    if [ $? -eq 0 ]; then \
-        echo "Ownership successfully changed for /workspace to ${IDE_USER}:${IDE_USER}"; \
-    else \
-        echo "Failed to change ownership for /workspace"; \
-    fi && \
-    chmod -R u+rw /workspace
+# # Ensure the IDE_USER has ownership of the workspace directory - dont know if this works. copilot says it cannot be done
+# # only echo out the status if in debug mode
+# RUN set -eux && \
+#     echo "Fixing ownership and permissions for /workspace..." && \
+#     chown -R ${IDE_USER}:${IDE_USER} /workspace && \
+#     if [ $? -eq 0 ]; then \
+#         echo "Ownership successfully changed for /workspace to ${IDE_USER}:${IDE_USER}"; \
+#     else \
+#         echo "Failed to change ownership for /workspace"; \
+#     fi && \
+#     chmod -R u+rw /workspace
 
-# Switch to the non-root user running vscode
-# This is important for security and to avoid permission issues
-# The user should have the same UID and GID as the host user
-# This allows the container to access files on the host without permission issues
-USER ${IDE_USER}
-# Build the solution in Debug mode
-# The --no-incremental option is used to force a full rebuild
-# This is useful when you want to ensure that all projects are built from scratch
-# The -c Debug option specifies the configuration to use (Debug or Release)
-RUN dotnet build /workspace/src/NopCommerce.sln --no-incremental -c Debug
+# # Switch to the non-root user running vscode
+# # This is important for security and to avoid permission issues
+# # The user should have the same UID and GID as the host user
+# # This allows the container to access files on the host without permission issues
+# USER ${IDE_USER}
+# # Build the solution in Debug mode
+# # The --no-incremental option is used to force a full rebuild
+# # This is useful when you want to ensure that all projects are built from scratch
+# # The -c Debug option specifies the configuration to use (Debug or Release)
+# RUN dotnet build /workspace/src/NopCommerce.sln --no-incremental -c Debug
 
-# Build the projects separately to avoid dependency issues (only if needed for debugging)
-# Note: The --no-incremental flag is used to force a full rebuild
-# This is useful when you want to ensure that all projects are built from scratch
-# Build the projects in the correct order to avoid dependency issues
-# leave commented out until needed for debugging
-#RUN dotnet build ./src/Presentation/Nop.Web.Framework/Themes/Nop.Web.Framework.Themes.csproj --no-incremental -c Debug -o ./bin/Presentation/Nop.Web.Framework.Themes
-#RUN do/net build ./sr//Presentation//op.Web.Framewo/k/Themes/Nop.W/b.Framework.Th/mes.Libraries/Nop.Web.Framework.Themes.Libraries.csproj --no-incremental -c Debug -o ./bin/Presentation/Nop.Web.Framework.Themes/Nop.Web.Framework.Themes.Libraries
-#RUN dotnet build ./src/Presentation/Nop.Web.Framework/Nop.Web.Framework.csproj --no-incremental -c Debug -o ./bin/Presentation/Nop.Web.Framework
-#RUN dotnet build ./src/Presentation/Nop.Web/Nop.Web.csproj --no-incremental -c Debug -o ./bin/Presentation/Nop.Web
-#RUN dotnet build ./src/Libraries/Nop.Services/Nop.Services.csproj --no-incremental -c Debug -o ./bin/Libraries/Nop.Services
-#RUN dotnet build ./src/Libraries/Nop.Core/Nop.Core.csproj --no-incremental -c Debug -o ./bin/Libraries/Nop.Core
-#RUN dotnet build ./src/Libraries/Nop.Data/Nop.Data.csproj --no-incremental -c Debug -o ./bin/Libraries/Nop.Data
 
-# Copy the contents of ./src to ./bin as the non-root user
-# This is important to avoid permission issues when removing this folder using the entrypoint script which runs under the IDE_USER
-USER ${IDE_USER}
-RUN mkdir ./bin && cp -r ./src/* ./bin/
-CMD ["./.devcontainer/containers/Nop.Web/entrypoint.sh"]
+# # Nop gets built into the src folder. So we have to copy this over to the /bin folder
+# RUN mkdir ./bin && cp -r ./src/* ./bin/ && \
+#     echo "Contents of ./src have been copied to ./bin."
+
+# Set the entrypoint script
+#ENTRYPOINT ["./.devcontainer/containers/Nop.Web/entrypoint.sh"]
+
+# Default command to keep the container running after the entrypoint finishes
+# this is overriding the entrypoint command from devcontainer.json
+# This will only run if you use docker-compose up and not devcontainer up thru vscode
+CMD ["tail", "-f", "/dev/null"]
